sudo: required
services:
 - docker

before_install:
 - docker build -t mdockertest/react-test -f ./client/Dockerfile.dev ./client

script:
 - docker run mdockertest/react-test npm test -- --coverage

after_success:
 - docker build -t mdockertest/multi-client ./client
 - docker build -t mdockertest/multi-nginx ./nginx
 - docker build -t mdockertest/multi-server ./server
 - docker build -t mdockertest/multi-worker ./worker

# Log in to the docker CLI
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Take those images and push them to docker hub
 - docker tag mdockertest/multi-client andrey0607/mdockertest:multi-client
 - docker tag mdockertest/multi-nginx andrey0607/mdockertest:multi-nginx
 - docker tag mdockertest/multi-server andrey0607/mdockertest:multi-server
 - docker tag mdockertest/multi-worker andrey0607/mdockertest:multi-worker
 - docker push andrey0607/multi-client
 - docker push andrey0607/multi-nginx
 - docker push andrey0607/multi-server
 - docker push andrey0607/multi-worker

deploy:
 provider: elasticbeanstalk
 region: "us-east-2"
 app: "multi-docker"
 env: "MultiDocker-env"
 bucket_name: "elasticbeanstalk-us-east-2-509292574433"
 bucket_path: "docker-multi"
 on:
  branch: master
 access_key_id: $AWS_ACCESS_KEY
 secret_access_key:
  secure: "$AWS_SECRET_KEY"
