sudo: required
services:
 - docker

before_install:
 - docker build -t mdockertest/react-test -f ./client/Dockerfile.dev ./client

script:
 - docker run mdockertest/react-test npm test -- --coverage

after_success:
 - docker build -t mdockertest/multi-client ./client
 - docker build -t mdockertest/multi-nginx ./nginx
 - docker build -t mdockertest/multi-server ./server
 - docker build -t mdockertest/multi-worker ./worker

# Log in to the docker CLI
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Take those images and push them to docker hub
 - docker push mdockertest/multi-client
 - docker push mdockertest/multi-nginx
 - docker push mdockertest/multi-server
 - docker push mdockertest/multi-worker
